doc: Update README.md
kairoaraujo/goca pull request #36
Opened 2024-03-11 02:56 UTC by ZenkieBear

We should use `go get github.com/xxx` to fetch go packages. If you add the http protocol before the domain, GoLang will print a error.

2024-03-13 19:58 UTC, kairoaraujo approved these changes

2024-04-06 15:29 UTC, necheffa requested changes
I believe there needs to be a `v2` sub-directory on the package path for this to work as intended. Particularly after PR35 is merged.

e.g. `go get github.com/kairoaraujo/goca/v2@v2.0.0`

The v2.0.0 probably won't work either due to the issue you fixed with PR35. What do you say about making the version "latest"?

2024-04-07 01:29 UTC, ZenkieBear commented
> I believe there needs to be a `v2` sub-directory on the package path for this to work as intended. Particularly after PR35 is merged.
> 
> e.g. `go get github.com/kairoaraujo/goca/v2@v2.0.0`
> 
> The v2.0.0 probably won't work either due to the issue you fixed with PR35. What do you say about making the version "latest"?

That's a great idea

2024-04-07 18:16 UTC, necheffa approved these changes
LGTM

2024-04-07 18:17 UTC, merged